steps:
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'minehub-frontend'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    dir: 'minehub-frontend'
    args: ['run', 'build']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', 'minehub-frontend/build/', 'gs://minehub-frontend']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['web', 'set', '-m', 'index.html', '-e', '404.html', 'gs://minehub-frontend']

images: []

options:
  logging: CLOUD_LOGGING_ONLY
