steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'minehub-frontend'   # This specifies that the npm commands will be executed inside the 'minehub-frontend' folder
    args: ['install']

  # Step 2: Build React app
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'minehub-frontend'   # Same here: build will run in the 'minehub-frontend' directory
    args: ['run', 'build']

  # Step 3: Deploy build output to your GCS bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', 'minehub-frontend/', 'gs://minehub-frontend']

  # Step 4: Set GCS static website metadata
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['web', 'set', '-m', 'index.html', '-e', '404.html', 'gs://minehub-frontend']

images: []

options:
  logging: CLOUD_LOGGING_ONLY
