services:
  - type: static
    name: minehub-frontend
    env: static
    staticPublishPath: build
    buildCommand: npm install && npm run build
    branch: main

  - type: web
    name: minehub-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn minehub.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: minehub.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        value: your-production-secret-key
      - key: DEBUG
        value: False
